trigger:
  branches:
    include:
      - development
      - main
      - features/*

name: $(Date:yyyy.MM.dd).$(rev:rr)

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.10.0'
    displayName: 'Install Node.js'

  - task: DownloadSecureFile@1
    inputs:
      secureFile: '.env'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: '.env'
      TargetFolder: '$(Build.SourcesDirectory)'

  - script: |
      ls -la
      npm ci
      npm run build
    displayName: 'Build erfantacalcio'

  - task: CopyFiles@2
    inputs:
      Contents: '.next/**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'erfantacalcio'
      publishLocation: 'Container'
