import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration.ts1763205256538 implements MigrationInterface {
    name = 'InitialMigration.ts1763205256538'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Trasferimenti" DROP CONSTRAINT "FK_Trasferimenti_Giocatori"`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" DROP CONSTRAINT "FK_Trasferimenti_SquadreSerieA"`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" DROP CONSTRAINT "FK_Trasferimenti_Utenti"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP CONSTRAINT "FK_Formazione_Giocatori"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP CONSTRAINT "FK_Voti_Calendario"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP CONSTRAINT "FK_Voti_Giocatori"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP CONSTRAINT "FK_Formazioni_Partite"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP CONSTRAINT "FK_Formazioni_Utenti"`);
        await queryRunner.query(`ALTER TABLE "Partite" DROP CONSTRAINT "FK_Partite_Calendario"`);
        await queryRunner.query(`ALTER TABLE "Partite" DROP CONSTRAINT "FK_Partite_SquadreCasa"`);
        await queryRunner.query(`ALTER TABLE "Partite" DROP CONSTRAINT "FK_Partite_SquadreTrasferta"`);
        await queryRunner.query(`ALTER TABLE "Calendario" DROP CONSTRAINT "FK_Calendario_Tornei"`);
        await queryRunner.query(`ALTER TABLE "Classifiche" DROP CONSTRAINT "FK_Classifiche_Tornei"`);
        await queryRunner.query(`ALTER TABLE "Classifiche" DROP CONSTRAINT "FK_Classifiche_Utenti"`);
        await queryRunner.query(`DROP INDEX "public"."IX_SquadreSerieA_idSquadraSerieA"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Trasferimenti_idTrasferimento"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Giocatori_idGiocatore"`);
        await queryRunner.query(`DROP INDEX "public"."UNIQUE_GIOCATORI_NOME"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Voti_idVoto"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Formazioni_idFormazione"`);
        await queryRunner.query(`DROP INDEX "public"."UNIQUE_Formazioni_ids"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Partite_idPartita"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Calendario_idCalendario"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Tornei_idTorneo"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Utenti"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Utenti_idUtente"`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ADD "giocatoriIdGiocatore" integer`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ADD "squadreSerieAIdSquadraSerieA" integer`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ADD "utentiIdUtente" integer`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD "formazioniIdFormazione" integer`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD "calendarioIdCalendario" integer`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD "giocatoriIdGiocatore" integer`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD "partiteIdPartita" integer`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD "utentiIdUtente" integer`);
        await queryRunner.query(`ALTER TABLE "Calendario" ADD "torneiIdTorneo" integer`);
        await queryRunner.query(`ALTER TABLE "Classifiche" ADD "torneiIdTorneo" integer`);
        await queryRunner.query(`ALTER TABLE "Classifiche" ADD "utentiIdUtente" integer`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ALTER COLUMN "dataAcquisto" TYPE TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ALTER COLUMN "dataAcquisto" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ALTER COLUMN "dataCessione" TYPE TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Giocatori" ADD CONSTRAINT "UQ_45ace405cb62d43dbe932411207" UNIQUE ("nome")`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ALTER COLUMN "dataOra" TYPE TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ALTER COLUMN "dataOra" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "Calendario" ALTER COLUMN "data" TYPE TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Calendario" ALTER COLUMN "data" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "Calendario" ALTER COLUMN "dataFine" TYPE TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD CONSTRAINT "UNIQUE_Formazioni_ids" UNIQUE ("idSquadra", "idPartita")`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ADD CONSTRAINT "FK_226ea13594cd2937450452f3749" FOREIGN KEY ("giocatoriIdGiocatore") REFERENCES "Giocatori"("idGiocatore") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ADD CONSTRAINT "FK_cbfff39342d02a3b0e61feae084" FOREIGN KEY ("squadreSerieAIdSquadraSerieA") REFERENCES "SquadreSerieA"("idSquadraSerieA") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ADD CONSTRAINT "FK_4714f9ba0fd193c23b7d019f830" FOREIGN KEY ("utentiIdUtente") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD CONSTRAINT "FK_1ea7c35a3db0f69892d06994ef3" FOREIGN KEY ("formazioniIdFormazione") REFERENCES "Formazioni"("idFormazione") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD CONSTRAINT "FK_cfe4f226d125d9e85ce774483da" FOREIGN KEY ("calendarioIdCalendario") REFERENCES "Calendario"("idCalendario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD CONSTRAINT "FK_bd02a596a9487f3e4cc3c640ca5" FOREIGN KEY ("giocatoriIdGiocatore") REFERENCES "Giocatori"("idGiocatore") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD CONSTRAINT "FK_0fb1660906cc3de75e35bd0081c" FOREIGN KEY ("partiteIdPartita") REFERENCES "Partite"("idPartita") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD CONSTRAINT "FK_161d7d78f610158e7c99511f898" FOREIGN KEY ("utentiIdUtente") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Partite" ADD CONSTRAINT "FK_fa8a2c70a61b52d368f88f45562" FOREIGN KEY ("idCalendario") REFERENCES "Calendario"("idCalendario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Partite" ADD CONSTRAINT "FK_6e36392329c80dd174023c65f67" FOREIGN KEY ("idSquadraH") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Partite" ADD CONSTRAINT "FK_baccc1f39f73bfc2306efeba666" FOREIGN KEY ("idSquadraA") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Calendario" ADD CONSTRAINT "FK_500629dd3d68ebc8cb59e2418e0" FOREIGN KEY ("torneiIdTorneo") REFERENCES "Tornei"("idTorneo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Classifiche" ADD CONSTRAINT "FK_0164e2c1ecc5b53824e5595fc26" FOREIGN KEY ("torneiIdTorneo") REFERENCES "Tornei"("idTorneo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Classifiche" ADD CONSTRAINT "FK_d225aaadcf6a801f00b8576ad42" FOREIGN KEY ("utentiIdUtente") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Classifiche" DROP CONSTRAINT "FK_d225aaadcf6a801f00b8576ad42"`);
        await queryRunner.query(`ALTER TABLE "Classifiche" DROP CONSTRAINT "FK_0164e2c1ecc5b53824e5595fc26"`);
        await queryRunner.query(`ALTER TABLE "Calendario" DROP CONSTRAINT "FK_500629dd3d68ebc8cb59e2418e0"`);
        await queryRunner.query(`ALTER TABLE "Partite" DROP CONSTRAINT "FK_baccc1f39f73bfc2306efeba666"`);
        await queryRunner.query(`ALTER TABLE "Partite" DROP CONSTRAINT "FK_6e36392329c80dd174023c65f67"`);
        await queryRunner.query(`ALTER TABLE "Partite" DROP CONSTRAINT "FK_fa8a2c70a61b52d368f88f45562"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP CONSTRAINT "FK_161d7d78f610158e7c99511f898"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP CONSTRAINT "FK_0fb1660906cc3de75e35bd0081c"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP CONSTRAINT "FK_bd02a596a9487f3e4cc3c640ca5"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP CONSTRAINT "FK_cfe4f226d125d9e85ce774483da"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP CONSTRAINT "FK_1ea7c35a3db0f69892d06994ef3"`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" DROP CONSTRAINT "FK_4714f9ba0fd193c23b7d019f830"`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" DROP CONSTRAINT "FK_cbfff39342d02a3b0e61feae084"`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" DROP CONSTRAINT "FK_226ea13594cd2937450452f3749"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP CONSTRAINT "UNIQUE_Formazioni_ids"`);
        await queryRunner.query(`ALTER TABLE "Calendario" ALTER COLUMN "dataFine" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Calendario" ALTER COLUMN "data" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "Calendario" ALTER COLUMN "data" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ALTER COLUMN "dataOra" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ALTER COLUMN "dataOra" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Giocatori" DROP CONSTRAINT "UQ_45ace405cb62d43dbe932411207"`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ALTER COLUMN "dataCessione" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ALTER COLUMN "dataAcquisto" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ALTER COLUMN "dataAcquisto" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Classifiche" DROP COLUMN "utentiIdUtente"`);
        await queryRunner.query(`ALTER TABLE "Classifiche" DROP COLUMN "torneiIdTorneo"`);
        await queryRunner.query(`ALTER TABLE "Calendario" DROP COLUMN "torneiIdTorneo"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP COLUMN "utentiIdUtente"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP COLUMN "partiteIdPartita"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP COLUMN "giocatoriIdGiocatore"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP COLUMN "calendarioIdCalendario"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP COLUMN "formazioniIdFormazione"`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" DROP COLUMN "utentiIdUtente"`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" DROP COLUMN "squadreSerieAIdSquadraSerieA"`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" DROP COLUMN "giocatoriIdGiocatore"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Utenti_idUtente" ON "Utenti" ("idUtente") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Utenti" ON "Utenti" ("username", "pwd") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Tornei_idTorneo" ON "Tornei" ("idTorneo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Calendario_idCalendario" ON "Calendario" ("idCalendario") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Partite_idPartita" ON "Partite" ("idPartita") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UNIQUE_Formazioni_ids" ON "Formazioni" ("idSquadra", "idPartita") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Formazioni_idFormazione" ON "Formazioni" ("idFormazione") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Voti_idVoto" ON "Voti" ("idVoto") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UNIQUE_GIOCATORI_NOME" ON "Giocatori" ("nome") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Giocatori_idGiocatore" ON "Giocatori" ("idGiocatore") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Trasferimenti_idTrasferimento" ON "Trasferimenti" ("idTrasferimento") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_SquadreSerieA_idSquadraSerieA" ON "SquadreSerieA" ("idSquadraSerieA") `);
        await queryRunner.query(`ALTER TABLE "Classifiche" ADD CONSTRAINT "FK_Classifiche_Utenti" FOREIGN KEY ("idSquadra") REFERENCES "Utenti"("idUtente") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Classifiche" ADD CONSTRAINT "FK_Classifiche_Tornei" FOREIGN KEY ("idTorneo") REFERENCES "Tornei"("idTorneo") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Calendario" ADD CONSTRAINT "FK_Calendario_Tornei" FOREIGN KEY ("idTorneo") REFERENCES "Tornei"("idTorneo") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Partite" ADD CONSTRAINT "FK_Partite_SquadreTrasferta" FOREIGN KEY ("idSquadraA") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Partite" ADD CONSTRAINT "FK_Partite_SquadreCasa" FOREIGN KEY ("idSquadraH") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Partite" ADD CONSTRAINT "FK_Partite_Calendario" FOREIGN KEY ("idCalendario") REFERENCES "Calendario"("idCalendario") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD CONSTRAINT "FK_Formazioni_Utenti" FOREIGN KEY ("idSquadra") REFERENCES "Utenti"("idUtente") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD CONSTRAINT "FK_Formazioni_Partite" FOREIGN KEY ("idPartita") REFERENCES "Partite"("idPartita") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD CONSTRAINT "FK_Voti_Giocatori" FOREIGN KEY ("idGiocatore") REFERENCES "Giocatori"("idGiocatore") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD CONSTRAINT "FK_Voti_Calendario" FOREIGN KEY ("idCalendario") REFERENCES "Calendario"("idCalendario") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD CONSTRAINT "FK_Formazione_Giocatori" FOREIGN KEY ("idFormazione") REFERENCES "Formazioni"("idFormazione") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ADD CONSTRAINT "FK_Trasferimenti_Utenti" FOREIGN KEY ("idSquadra") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ADD CONSTRAINT "FK_Trasferimenti_SquadreSerieA" FOREIGN KEY ("idSquadraSerieA") REFERENCES "SquadreSerieA"("idSquadraSerieA") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ADD CONSTRAINT "FK_Trasferimenti_Giocatori" FOREIGN KEY ("idGiocatore") REFERENCES "Giocatori"("idGiocatore") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

}
