import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1763368518761 implements MigrationInterface {
    name = 'InitialMigration1763368518761'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Classifiche" DROP CONSTRAINT "FK_Classifiche_Tornei"`);
        await queryRunner.query(`ALTER TABLE "Classifiche" DROP CONSTRAINT "FK_Classifiche_Utenti"`);
        await queryRunner.query(`ALTER TABLE "Calendario" DROP CONSTRAINT "FK_Calendario_Tornei"`);
        await queryRunner.query(`ALTER TABLE "Partite" DROP CONSTRAINT "FK_Partite_Calendario"`);
        await queryRunner.query(`ALTER TABLE "Partite" DROP CONSTRAINT "FK_Partite_SquadreCasa"`);
        await queryRunner.query(`ALTER TABLE "Partite" DROP CONSTRAINT "FK_Partite_SquadreTrasferta"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP CONSTRAINT "FK_Formazioni_Partite"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP CONSTRAINT "FK_Formazioni_Utenti"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP CONSTRAINT "FK_Formazione_Giocatori"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP CONSTRAINT "FK_Voti_Calendario"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP CONSTRAINT "FK_Voti_Giocatori"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Giocatori_idGiocatore"`);
        await queryRunner.query(`DROP INDEX "public"."UNIQUE_GIOCATORI_NOME"`);
        await queryRunner.query(`DROP INDEX "public"."IX_SquadreSerieA_idSquadraSerieA"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Trasferimenti_idTrasferimento"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Utenti"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Utenti_idUtente"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Tornei_idTorneo"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Calendario_idCalendario"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Partite_idPartita"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Formazioni_idFormazione"`);
        await queryRunner.query(`DROP INDEX "public"."UNIQUE_Formazioni_ids"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Voti_idVoto"`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ADD "idUtente" integer`);
        await queryRunner.query(`ALTER TABLE "Classifiche" ADD "torneiIdTorneo" integer`);
        await queryRunner.query(`ALTER TABLE "Classifiche" ADD "utentiIdUtente" integer`);
        await queryRunner.query(`ALTER TABLE "Calendario" ADD "torneiIdTorneo" integer`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD "partiteIdPartita" integer`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD "utentiIdUtente" integer`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD "formazioniIdFormazione" integer`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD "calendarioIdCalendario" integer`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD "giocatoriIdGiocatore" integer`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "SerieA_idSerieA_seq" OWNED BY "SerieA"."idSerieA"`);
        await queryRunner.query(`ALTER TABLE "SerieA" ALTER COLUMN "idSerieA" SET DEFAULT nextval('"SerieA_idSerieA_seq"')`);
        await queryRunner.query(`ALTER TABLE "SerieA" ALTER COLUMN "idSerieA" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "FlowNewSeasosn" ALTER COLUMN "data" TYPE TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "FlowNewSeasosn" ALTER COLUMN "data" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "Giocatori" ADD CONSTRAINT "UQ_45ace405cb62d43dbe932411207" UNIQUE ("nome")`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ALTER COLUMN "dataAcquisto" TYPE TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ALTER COLUMN "dataAcquisto" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ALTER COLUMN "dataCessione" TYPE TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Calendario" ALTER COLUMN "data" TYPE TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Calendario" ALTER COLUMN "data" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "Calendario" ALTER COLUMN "dataFine" TYPE TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ALTER COLUMN "dataOra" TYPE TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ALTER COLUMN "dataOra" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "AlboTrofei_new_id_seq" OWNED BY "AlboTrofei_new"."id"`);
        await queryRunner.query(`ALTER TABLE "AlboTrofei_new" ALTER COLUMN "id" SET DEFAULT nextval('"AlboTrofei_new_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "AlboTrofei_new" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE UNIQUE INDEX "PK_StatsP" ON "StatsP" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "PK_StatsD" ON "StatsD" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "PK_StatsC" ON "StatsC" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "PK_StatsA" ON "StatsA" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "PK_SerieA" ON "SerieA" ("idSerieA") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "PK_FlowNewSeason" ON "FlowNewSeasosn" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "PK_AlboTrofei_new" ON "AlboTrofei_new" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "PK_AlboTrofei" ON "AlboTrofei" ("id") `);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD CONSTRAINT "UNIQUE_Formazioni_ids" UNIQUE ("idSquadra", "idPartita")`);
        await queryRunner.query(`ALTER TABLE "Classifiche" ADD CONSTRAINT "FK_Tornei" FOREIGN KEY ("torneiIdTorneo") REFERENCES "Tornei"("idTorneo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Classifiche" ADD CONSTRAINT "FK_Utenti" FOREIGN KEY ("utentiIdUtente") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Calendario" ADD CONSTRAINT "FK_Tornei" FOREIGN KEY ("torneiIdTorneo") REFERENCES "Tornei"("idTorneo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Partite" ADD CONSTRAINT "FK_Calendario" FOREIGN KEY ("idCalendario") REFERENCES "Calendario"("idCalendario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Partite" ADD CONSTRAINT "FK_Utenti" FOREIGN KEY ("idSquadraH") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Partite" ADD CONSTRAINT "FK_Utenti" FOREIGN KEY ("idSquadraA") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD CONSTRAINT "FK_Partite" FOREIGN KEY ("partiteIdPartita") REFERENCES "Partite"("idPartita") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD CONSTRAINT "FK_Utenti" FOREIGN KEY ("utentiIdUtente") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD CONSTRAINT "FK_Formazioni" FOREIGN KEY ("formazioniIdFormazione") REFERENCES "Formazioni"("idFormazione") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD CONSTRAINT "FK_Calendario" FOREIGN KEY ("calendarioIdCalendario") REFERENCES "Calendario"("idCalendario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD CONSTRAINT "FK_Giocatori" FOREIGN KEY ("giocatoriIdGiocatore") REFERENCES "Giocatori"("idGiocatore") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Voti" DROP CONSTRAINT "FK_Giocatori"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP CONSTRAINT "FK_Calendario"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP CONSTRAINT "FK_Formazioni"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP CONSTRAINT "FK_Utenti"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP CONSTRAINT "FK_Partite"`);
        await queryRunner.query(`ALTER TABLE "Partite" DROP CONSTRAINT "FK_Utenti"`);
        await queryRunner.query(`ALTER TABLE "Partite" DROP CONSTRAINT "FK_Utenti"`);
        await queryRunner.query(`ALTER TABLE "Partite" DROP CONSTRAINT "FK_Calendario"`);
        await queryRunner.query(`ALTER TABLE "Calendario" DROP CONSTRAINT "FK_Tornei"`);
        await queryRunner.query(`ALTER TABLE "Classifiche" DROP CONSTRAINT "FK_Utenti"`);
        await queryRunner.query(`ALTER TABLE "Classifiche" DROP CONSTRAINT "FK_Tornei"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP CONSTRAINT "UNIQUE_Formazioni_ids"`);
        await queryRunner.query(`DROP INDEX "public"."PK_AlboTrofei"`);
        await queryRunner.query(`DROP INDEX "public"."PK_AlboTrofei_new"`);
        await queryRunner.query(`DROP INDEX "public"."PK_FlowNewSeason"`);
        await queryRunner.query(`DROP INDEX "public"."PK_SerieA"`);
        await queryRunner.query(`DROP INDEX "public"."PK_StatsA"`);
        await queryRunner.query(`DROP INDEX "public"."PK_StatsC"`);
        await queryRunner.query(`DROP INDEX "public"."PK_StatsD"`);
        await queryRunner.query(`DROP INDEX "public"."PK_StatsP"`);
        await queryRunner.query(`ALTER TABLE "AlboTrofei_new" ALTER COLUMN "id" SET DEFAULT nextval('"AlboTrofei_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "AlboTrofei_new" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "AlboTrofei_new_id_seq"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ALTER COLUMN "dataOra" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ALTER COLUMN "dataOra" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Calendario" ALTER COLUMN "dataFine" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Calendario" ALTER COLUMN "data" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "Calendario" ALTER COLUMN "data" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ALTER COLUMN "dataCessione" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ALTER COLUMN "dataAcquisto" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" ALTER COLUMN "dataAcquisto" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Giocatori" DROP CONSTRAINT "UQ_45ace405cb62d43dbe932411207"`);
        await queryRunner.query(`ALTER TABLE "FlowNewSeasosn" ALTER COLUMN "data" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "FlowNewSeasosn" ALTER COLUMN "data" TYPE TIMESTAMP(3) WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "SerieA" ALTER COLUMN "idSerieA" SET DEFAULT nextval('"SerieA_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "SerieA" ALTER COLUMN "idSerieA" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "SerieA_idSerieA_seq"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP COLUMN "giocatoriIdGiocatore"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP COLUMN "calendarioIdCalendario"`);
        await queryRunner.query(`ALTER TABLE "Voti" DROP COLUMN "formazioniIdFormazione"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP COLUMN "utentiIdUtente"`);
        await queryRunner.query(`ALTER TABLE "Formazioni" DROP COLUMN "partiteIdPartita"`);
        await queryRunner.query(`ALTER TABLE "Calendario" DROP COLUMN "torneiIdTorneo"`);
        await queryRunner.query(`ALTER TABLE "Classifiche" DROP COLUMN "utentiIdUtente"`);
        await queryRunner.query(`ALTER TABLE "Classifiche" DROP COLUMN "torneiIdTorneo"`);
        await queryRunner.query(`ALTER TABLE "Trasferimenti" DROP COLUMN "idUtente"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Voti_idVoto" ON "Voti" ("idVoto") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UNIQUE_Formazioni_ids" ON "Formazioni" ("idSquadra", "idPartita") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Formazioni_idFormazione" ON "Formazioni" ("idFormazione") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Partite_idPartita" ON "Partite" ("idPartita") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Calendario_idCalendario" ON "Calendario" ("idCalendario") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Tornei_idTorneo" ON "Tornei" ("idTorneo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Utenti_idUtente" ON "Utenti" ("idUtente") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Utenti" ON "Utenti" ("username", "pwd") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Trasferimenti_idTrasferimento" ON "Trasferimenti" ("idTrasferimento") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_SquadreSerieA_idSquadraSerieA" ON "SquadreSerieA" ("idSquadraSerieA") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UNIQUE_GIOCATORI_NOME" ON "Giocatori" ("nome") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IX_Giocatori_idGiocatore" ON "Giocatori" ("idGiocatore") `);
        await queryRunner.query(`ALTER TABLE "Voti" ADD CONSTRAINT "FK_Voti_Giocatori" FOREIGN KEY ("idGiocatore") REFERENCES "Giocatori"("idGiocatore") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD CONSTRAINT "FK_Voti_Calendario" FOREIGN KEY ("idCalendario") REFERENCES "Calendario"("idCalendario") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Voti" ADD CONSTRAINT "FK_Formazione_Giocatori" FOREIGN KEY ("idFormazione") REFERENCES "Formazioni"("idFormazione") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD CONSTRAINT "FK_Formazioni_Utenti" FOREIGN KEY ("idSquadra") REFERENCES "Utenti"("idUtente") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Formazioni" ADD CONSTRAINT "FK_Formazioni_Partite" FOREIGN KEY ("idPartita") REFERENCES "Partite"("idPartita") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Partite" ADD CONSTRAINT "FK_Partite_SquadreTrasferta" FOREIGN KEY ("idSquadraA") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Partite" ADD CONSTRAINT "FK_Partite_SquadreCasa" FOREIGN KEY ("idSquadraH") REFERENCES "Utenti"("idUtente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Partite" ADD CONSTRAINT "FK_Partite_Calendario" FOREIGN KEY ("idCalendario") REFERENCES "Calendario"("idCalendario") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Calendario" ADD CONSTRAINT "FK_Calendario_Tornei" FOREIGN KEY ("idTorneo") REFERENCES "Tornei"("idTorneo") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Classifiche" ADD CONSTRAINT "FK_Classifiche_Utenti" FOREIGN KEY ("idSquadra") REFERENCES "Utenti"("idUtente") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Classifiche" ADD CONSTRAINT "FK_Classifiche_Tornei" FOREIGN KEY ("idTorneo") REFERENCES "Tornei"("idTorneo") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

}
