import { MigrationInterface, QueryRunner } from "typeorm";

export class AddIndexes1764087897632 implements MigrationInterface {
    name = 'AddIndexes1764087897632'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IX_Voti_StatsGiocatori"`);
        await queryRunner.query(`DROP INDEX "public"."IX_Voti_StatsGiocatori2"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "albo_trofei_id_seq"`);
        await queryRunner.query(`ALTER TABLE "albo_trofei" ALTER COLUMN "id" SET DEFAULT nextval('"albo_trofei_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "albo_trofei" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "formazione" DROP CONSTRAINT "FK_Formazioni_Partite"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "partita_id_partita_seq"`);
        await queryRunner.query(`ALTER TABLE "partita" ALTER COLUMN "id_partita" SET DEFAULT nextval('"partita_id_partita_seq"')`);
        await queryRunner.query(`ALTER TABLE "partita" ALTER COLUMN "id_partita" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "voto" DROP CONSTRAINT "FK_Formazione_Giocatori"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "formazione_id_formazione_seq"`);
        await queryRunner.query(`ALTER TABLE "formazione" ALTER COLUMN "id_formazione" SET DEFAULT nextval('"formazione_id_formazione_seq"')`);
        await queryRunner.query(`ALTER TABLE "formazione" ALTER COLUMN "id_formazione" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "voto_id_voto_seq"`);
        await queryRunner.query(`ALTER TABLE "voto" ALTER COLUMN "id_voto" SET DEFAULT nextval('"voto_id_voto_seq"')`);
        await queryRunner.query(`ALTER TABLE "voto" ALTER COLUMN "id_voto" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "voto" DROP CONSTRAINT "FK_Voti_Giocatori"`);
        await queryRunner.query(`ALTER TABLE "trasferimento" DROP CONSTRAINT "FK_Trasferimenti_Giocatori"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "giocatore_id_giocatore_seq"`);
        await queryRunner.query(`ALTER TABLE "giocatore" ALTER COLUMN "id_giocatore" SET DEFAULT nextval('"giocatore_id_giocatore_seq"')`);
        await queryRunner.query(`ALTER TABLE "giocatore" ALTER COLUMN "id_giocatore" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "trasferimento" DROP CONSTRAINT "FK_Trasferimenti_SquadreSerieA"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "squadra_serie_a_id_squadra_serie_a_seq"`);
        await queryRunner.query(`ALTER TABLE "squadra_serie_a" ALTER COLUMN "id_squadra_serie_a" SET DEFAULT nextval('"squadra_serie_a_id_squadra_serie_a_seq"')`);
        await queryRunner.query(`ALTER TABLE "squadra_serie_a" ALTER COLUMN "id_squadra_serie_a" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "trasferimento_id_trasferimento_seq"`);
        await queryRunner.query(`ALTER TABLE "trasferimento" ALTER COLUMN "id_trasferimento" SET DEFAULT nextval('"trasferimento_id_trasferimento_seq"')`);
        await queryRunner.query(`ALTER TABLE "trasferimento" ALTER COLUMN "id_trasferimento" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "classifica" DROP CONSTRAINT "FK_Classifiche_Utenti"`);
        await queryRunner.query(`ALTER TABLE "trasferimento" DROP CONSTRAINT "FK_Trasferimenti_Utenti"`);
        await queryRunner.query(`ALTER TABLE "formazione" DROP CONSTRAINT "FK_Formazioni_Utenti"`);
        await queryRunner.query(`ALTER TABLE "partita" DROP CONSTRAINT "FK_Partite_SquadreCasa"`);
        await queryRunner.query(`ALTER TABLE "partita" DROP CONSTRAINT "FK_Partite_SquadreTrasferta"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "utente_id_utente_seq"`);
        await queryRunner.query(`ALTER TABLE "utente" ALTER COLUMN "id_utente" SET DEFAULT nextval('"utente_id_utente_seq"')`);
        await queryRunner.query(`ALTER TABLE "utente" ALTER COLUMN "id_utente" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "classifica_id_seq"`);
        await queryRunner.query(`ALTER TABLE "classifica" ALTER COLUMN "id" SET DEFAULT nextval('"classifica_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "classifica" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "classifica" DROP CONSTRAINT "FK_Classifiche_Tornei"`);
        await queryRunner.query(`ALTER TABLE "calendario" DROP CONSTRAINT "FK_Calendario_Tornei"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "torneo_id_torneo_seq"`);
        await queryRunner.query(`ALTER TABLE "torneo" ALTER COLUMN "id_torneo" SET DEFAULT nextval('"torneo_id_torneo_seq"')`);
        await queryRunner.query(`ALTER TABLE "torneo" ALTER COLUMN "id_torneo" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "voto" DROP CONSTRAINT "FK_Voti_Calendario"`);
        await queryRunner.query(`ALTER TABLE "partita" DROP CONSTRAINT "FK_Partite_Calendario"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "calendario_id_calendario_seq"`);
        await queryRunner.query(`ALTER TABLE "calendario" ALTER COLUMN "id_calendario" SET DEFAULT nextval('"calendario_id_calendario_seq"')`);
        await queryRunner.query(`ALTER TABLE "calendario" ALTER COLUMN "id_calendario" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "flow_new_season_id_seq"`);
        await queryRunner.query(`ALTER TABLE "flow_new_season" ALTER COLUMN "id" SET DEFAULT nextval('"flow_new_season_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "flow_new_season" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "stats_p_id_seq"`);
        await queryRunner.query(`ALTER TABLE "stats_p" ALTER COLUMN "id" SET DEFAULT nextval('"stats_p_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "stats_p" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "stats_d_id_seq"`);
        await queryRunner.query(`ALTER TABLE "stats_d" ALTER COLUMN "id" SET DEFAULT nextval('"stats_d_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "stats_d" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "stats_c_id_seq"`);
        await queryRunner.query(`ALTER TABLE "stats_c" ALTER COLUMN "id" SET DEFAULT nextval('"stats_c_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "stats_c" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "stats_a_id_seq"`);
        await queryRunner.query(`ALTER TABLE "stats_a" ALTER COLUMN "id" SET DEFAULT nextval('"stats_a_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "stats_a" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "serie_a_id_serie_a_seq"`);
        await queryRunner.query(`ALTER TABLE "serie_a" ALTER COLUMN "id_serie_a" SET DEFAULT nextval('"serie_a_id_serie_a_seq"')`);
        await queryRunner.query(`ALTER TABLE "serie_a" ALTER COLUMN "id_serie_a" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "partita" ADD CONSTRAINT "FK_Partite_Calendario" FOREIGN KEY ("id_calendario") REFERENCES "calendario"("id_calendario") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partita" ADD CONSTRAINT "FK_Partite_SquadreCasa" FOREIGN KEY ("id_squadra_home") REFERENCES "utente"("id_utente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partita" ADD CONSTRAINT "FK_Partite_SquadreTrasferta" FOREIGN KEY ("id_squadra_away") REFERENCES "utente"("id_utente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formazione" ADD CONSTRAINT "FK_Formazioni_Partite" FOREIGN KEY ("id_partita") REFERENCES "partita"("id_partita") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formazione" ADD CONSTRAINT "FK_Formazioni_Utenti" FOREIGN KEY ("id_squadra") REFERENCES "utente"("id_utente") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voto" ADD CONSTRAINT "FK_Formazione_Giocatori" FOREIGN KEY ("id_formazione") REFERENCES "formazione"("id_formazione") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voto" ADD CONSTRAINT "FK_Voti_Calendario" FOREIGN KEY ("id_calendario") REFERENCES "calendario"("id_calendario") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voto" ADD CONSTRAINT "FK_Voti_Giocatori" FOREIGN KEY ("id_giocatore") REFERENCES "giocatore"("id_giocatore") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trasferimento" ADD CONSTRAINT "FK_Trasferimenti_Giocatori" FOREIGN KEY ("id_giocatore") REFERENCES "giocatore"("id_giocatore") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trasferimento" ADD CONSTRAINT "FK_Trasferimenti_SquadreSerieA" FOREIGN KEY ("id_squadra_serie_a") REFERENCES "squadra_serie_a"("id_squadra_serie_a") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trasferimento" ADD CONSTRAINT "FK_Trasferimenti_Utenti" FOREIGN KEY ("id_squadra") REFERENCES "utente"("id_utente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classifica" ADD CONSTRAINT "FK_Classifiche_Tornei" FOREIGN KEY ("id_torneo") REFERENCES "torneo"("id_torneo") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classifica" ADD CONSTRAINT "FK_Classifiche_Utenti" FOREIGN KEY ("id_squadra") REFERENCES "utente"("id_utente") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calendario" ADD CONSTRAINT "FK_Calendario_Tornei" FOREIGN KEY ("id_torneo") REFERENCES "torneo"("id_torneo") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "calendario" DROP CONSTRAINT "FK_Calendario_Tornei"`);
        await queryRunner.query(`ALTER TABLE "classifica" DROP CONSTRAINT "FK_Classifiche_Utenti"`);
        await queryRunner.query(`ALTER TABLE "classifica" DROP CONSTRAINT "FK_Classifiche_Tornei"`);
        await queryRunner.query(`ALTER TABLE "trasferimento" DROP CONSTRAINT "FK_Trasferimenti_Utenti"`);
        await queryRunner.query(`ALTER TABLE "trasferimento" DROP CONSTRAINT "FK_Trasferimenti_SquadreSerieA"`);
        await queryRunner.query(`ALTER TABLE "trasferimento" DROP CONSTRAINT "FK_Trasferimenti_Giocatori"`);
        await queryRunner.query(`ALTER TABLE "voto" DROP CONSTRAINT "FK_Voti_Giocatori"`);
        await queryRunner.query(`ALTER TABLE "voto" DROP CONSTRAINT "FK_Voti_Calendario"`);
        await queryRunner.query(`ALTER TABLE "voto" DROP CONSTRAINT "FK_Formazione_Giocatori"`);
        await queryRunner.query(`ALTER TABLE "formazione" DROP CONSTRAINT "FK_Formazioni_Utenti"`);
        await queryRunner.query(`ALTER TABLE "formazione" DROP CONSTRAINT "FK_Formazioni_Partite"`);
        await queryRunner.query(`ALTER TABLE "partita" DROP CONSTRAINT "FK_Partite_SquadreTrasferta"`);
        await queryRunner.query(`ALTER TABLE "partita" DROP CONSTRAINT "FK_Partite_SquadreCasa"`);
        await queryRunner.query(`ALTER TABLE "partita" DROP CONSTRAINT "FK_Partite_Calendario"`);
        await queryRunner.query(`ALTER TABLE "serie_a" ALTER COLUMN "id_serie_a" SET DEFAULT nextval('"SerieA_idSerieA_seq"')`);
        await queryRunner.query(`ALTER TABLE "serie_a" ALTER COLUMN "id_serie_a" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "serie_a_id_serie_a_seq"`);
        await queryRunner.query(`ALTER TABLE "stats_a" ALTER COLUMN "id" SET DEFAULT nextval('"StatsA_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "stats_a" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "stats_a_id_seq"`);
        await queryRunner.query(`ALTER TABLE "stats_c" ALTER COLUMN "id" SET DEFAULT nextval('"StatsC_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "stats_c" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "stats_c_id_seq"`);
        await queryRunner.query(`ALTER TABLE "stats_d" ALTER COLUMN "id" SET DEFAULT nextval('"StatsD_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "stats_d" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "stats_d_id_seq"`);
        await queryRunner.query(`ALTER TABLE "stats_p" ALTER COLUMN "id" SET DEFAULT nextval('"StatsP_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "stats_p" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "stats_p_id_seq"`);
        await queryRunner.query(`ALTER TABLE "flow_new_season" ALTER COLUMN "id" SET DEFAULT nextval('"FlowNewSeasosn_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "flow_new_season" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "flow_new_season_id_seq"`);
        await queryRunner.query(`ALTER TABLE "calendario" ALTER COLUMN "id_calendario" SET DEFAULT nextval('"Calendario_idCalendario_seq"')`);
        await queryRunner.query(`ALTER TABLE "calendario" ALTER COLUMN "id_calendario" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "calendario_id_calendario_seq"`);
        await queryRunner.query(`ALTER TABLE "partita" ADD CONSTRAINT "FK_Partite_Calendario" FOREIGN KEY ("id_calendario") REFERENCES "calendario"("id_calendario") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voto" ADD CONSTRAINT "FK_Voti_Calendario" FOREIGN KEY ("id_calendario") REFERENCES "calendario"("id_calendario") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "torneo" ALTER COLUMN "id_torneo" SET DEFAULT nextval('"Tornei_idTorneo_seq"')`);
        await queryRunner.query(`ALTER TABLE "torneo" ALTER COLUMN "id_torneo" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "torneo_id_torneo_seq"`);
        await queryRunner.query(`ALTER TABLE "calendario" ADD CONSTRAINT "FK_Calendario_Tornei" FOREIGN KEY ("id_torneo") REFERENCES "torneo"("id_torneo") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classifica" ADD CONSTRAINT "FK_Classifiche_Tornei" FOREIGN KEY ("id_torneo") REFERENCES "torneo"("id_torneo") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classifica" ALTER COLUMN "id" SET DEFAULT nextval('"Classifiche_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "classifica" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "classifica_id_seq"`);
        await queryRunner.query(`ALTER TABLE "utente" ALTER COLUMN "id_utente" SET DEFAULT nextval('"Utenti_idUtente_seq"')`);
        await queryRunner.query(`ALTER TABLE "utente" ALTER COLUMN "id_utente" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "utente_id_utente_seq"`);
        await queryRunner.query(`ALTER TABLE "partita" ADD CONSTRAINT "FK_Partite_SquadreTrasferta" FOREIGN KEY ("id_squadra_away") REFERENCES "utente"("id_utente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partita" ADD CONSTRAINT "FK_Partite_SquadreCasa" FOREIGN KEY ("id_squadra_home") REFERENCES "utente"("id_utente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formazione" ADD CONSTRAINT "FK_Formazioni_Utenti" FOREIGN KEY ("id_squadra") REFERENCES "utente"("id_utente") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trasferimento" ADD CONSTRAINT "FK_Trasferimenti_Utenti" FOREIGN KEY ("id_squadra") REFERENCES "utente"("id_utente") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classifica" ADD CONSTRAINT "FK_Classifiche_Utenti" FOREIGN KEY ("id_squadra") REFERENCES "utente"("id_utente") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trasferimento" ALTER COLUMN "id_trasferimento" SET DEFAULT nextval('"Trasferimenti_idTrasferimento_seq"')`);
        await queryRunner.query(`ALTER TABLE "trasferimento" ALTER COLUMN "id_trasferimento" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "trasferimento_id_trasferimento_seq"`);
        await queryRunner.query(`ALTER TABLE "squadra_serie_a" ALTER COLUMN "id_squadra_serie_a" SET DEFAULT nextval('"SquadreSerieA_idSquadraSerieA_seq"')`);
        await queryRunner.query(`ALTER TABLE "squadra_serie_a" ALTER COLUMN "id_squadra_serie_a" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "squadra_serie_a_id_squadra_serie_a_seq"`);
        await queryRunner.query(`ALTER TABLE "trasferimento" ADD CONSTRAINT "FK_Trasferimenti_SquadreSerieA" FOREIGN KEY ("id_squadra_serie_a") REFERENCES "squadra_serie_a"("id_squadra_serie_a") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "giocatore" ALTER COLUMN "id_giocatore" SET DEFAULT nextval('"Giocatori_idGiocatore_seq"')`);
        await queryRunner.query(`ALTER TABLE "giocatore" ALTER COLUMN "id_giocatore" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "giocatore_id_giocatore_seq"`);
        await queryRunner.query(`ALTER TABLE "trasferimento" ADD CONSTRAINT "FK_Trasferimenti_Giocatori" FOREIGN KEY ("id_giocatore") REFERENCES "giocatore"("id_giocatore") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voto" ADD CONSTRAINT "FK_Voti_Giocatori" FOREIGN KEY ("id_giocatore") REFERENCES "giocatore"("id_giocatore") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voto" ALTER COLUMN "id_voto" SET DEFAULT nextval('"Voti_idVoto_seq"')`);
        await queryRunner.query(`ALTER TABLE "voto" ALTER COLUMN "id_voto" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "voto_id_voto_seq"`);
        await queryRunner.query(`ALTER TABLE "formazione" ALTER COLUMN "id_formazione" SET DEFAULT nextval('"Formazioni_idFormazione_seq"')`);
        await queryRunner.query(`ALTER TABLE "formazione" ALTER COLUMN "id_formazione" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "formazione_id_formazione_seq"`);
        await queryRunner.query(`ALTER TABLE "voto" ADD CONSTRAINT "FK_Formazione_Giocatori" FOREIGN KEY ("id_formazione") REFERENCES "formazione"("id_formazione") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "partita" ALTER COLUMN "id_partita" SET DEFAULT nextval('"Partite_idPartita_seq"')`);
        await queryRunner.query(`ALTER TABLE "partita" ALTER COLUMN "id_partita" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "partita_id_partita_seq"`);
        await queryRunner.query(`ALTER TABLE "formazione" ADD CONSTRAINT "FK_Formazioni_Partite" FOREIGN KEY ("id_partita") REFERENCES "partita"("id_partita") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "albo_trofei" ALTER COLUMN "id" SET DEFAULT nextval('"AlboTrofei_new_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "albo_trofei" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "albo_trofei_id_seq"`);
        await queryRunner.query(`CREATE INDEX "IX_Voti_StatsGiocatori2" ON "voto" ("id_giocatore") `);
        await queryRunner.query(`CREATE INDEX "IX_Voti_StatsGiocatori" ON "voto" ("voto") `);
    }

}
